arb-dir: lib\localization\l10n
template-arb-file: app_en.arb
output-dir: lib\localization\generated
output-localization-file: app_localizations.dart
synthetic-package: false
untranslated-messages-file: untranslated.json