name: Flutter_Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


env:
  GIPHY_API_KEY: ${{secrets.GIPHY_API_KEY}}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Restore packages
        run: flutter pub get

      - name: Add .env file
        run: echo "GIPHY_API_KEY=${GIPHY_API_KEY} TEST=true" > example/.env
        
      - name: Analyze
        run: flutter analyze
      
      
      - name: Run tests
        run: flutter test --coverage
      
        
